package com.example.animal_feed.order;

public enum State {
    ORDERED,
    REJECTED,
    CONFIRMED,
    PAID,
    DELIVERING,
    DELIVERED,
    CANCELLED,
    EXCHANGE_REQUESTED,
    EXCHANGE_APPROVED,
    EXCHANGE_REJECTED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
}
